### ISSUE TITLE
client authentication

### ISSUE THREAD

**Issue by aep** [Ralith/quicr#1]
any chance to implement client authentication?

**Comment by Ralith** [comment]
I should be able to add a callback for that pretty easily, yeah.

**Comment by aep** [comment]
any updates on this?

**Comment by Ralith** [comment]
Does 845d60ed5d2721d50017a6131fa7d356c838d610 help?

**Comment by bkchr** [comment]
Hmm, I think that the Rust way would be to provide a `Trait`. 

See for example: https://github.com/bkchr/picoquic-rs/blob/c38d6a8a683e4b697fe0d2e71e14f926d733710c/src/verify_certificate.rs#L10

Also you don't expose any way to match the client certificate to a connection?

**Comment by Ralith** [comment]
> Hmm, I think that the Rust way would be to provide a Trait.

That doesn't seem rustier to me. A trait defined with nothing but a single method like that is functionally equivalent to a closure, but requires more boilerplate.

> Also you don't expose any way to match the client certificate to a connection?

Interesting point. What's the use case? The obvious case of checking for a certain private CA, for example, doesn't to require that afaict.

**Comment by bkchr** [comment]
In Rust you even have cases where a `Trait` does not have any function at all. Maybe it is just a matter of taste.

For example when you want to use the certificate of a connection for other use cases, it is important to match a Connection to its certificate. You could for example use the certificate as an identifier of the connection.

**Comment by Ralith** [comment]
I feel like that would be better solved by exposing a certificate accessor on connections, similar to the ones currently exposed for SNI. The authentication callback should be concerned solely with the question of whether the certificate is acceptable at all.

**Comment by Ralith** [comment]
In lieu of any further comment from @aep, I think this is adequately solved for now.
