### ISSUE TITLE
Use rustls?

### ISSUE THREAD

**Issue by canndrew** [Ralith/quicr#3]
Rustls has [a branch](https://github.com/ctz/rustls/tree/jbp-tls13-draft-28) for TLS1.3 draft 28 support. The maintainer [says that](https://github.com/ctz/rustls/pull/166#issuecomment-382502271) he's waiting for boringssl to switch to using draft 28 by default before merging the branch into master, and [it looks like](https://boringssl.googlesource.com/boringssl/+/fec83fc78d489a8d444c3a99c51101fdf54d5b71) that has now happened. Would it be worth starting a branch for using rustls instead of native openssl and having it initially use the rustls draft 28 branch?

**Comment by Ralith** [comment]
rustls support would be great to have, both for ease of installation and ease of development. Right now the most important issue is support for [the new post draft-13 QUIC-TLS interface](https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#rfc.section.4.1), which neither rustls nor OpenSSL currently have. I've started looking into what will be necessary for rustls to expose this, and while it looks feasible so far, there's a lot about rustls's internals I don't have a great handle on yet.

**Comment by Ralith** [comment]
Work's begun at https://github.com/ctz/rustls/pull/187. Currently waiting on feedback from maintainers.

**Comment by canndrew** [comment]
Awesome! I'm really looking forward to being able to use QUIC with Rust. The problem I've had with quicr is not being able to install it due to needing an unreleased openssl. I'm on NixOS but I couldn't get the `shell.nix` file to work.

**Comment by Ralith** [comment]
That's odd, it should work out of the box at least on nixos-18.03. What fails?

**Comment by canndrew** [comment]
Oops, sorry for taking a while to get back to you. The output I get when it tries to build the openssl derivation is:

```
these derivations will be built:
  /nix/store/3scr6k66kicpa7r09iski3v5p5zd92pj-openssl-1.1.1-pre6.drv
building '/nix/store/3scr6k66kicpa7r09iski3v5p5zd92pj-openssl-1.1.1-pre6.drv'...
unpacking sources
unpacking source archive /nix/store/zyrqydcbalkv161zhgh725jwjws20hnw-source
source root is source
patching sources
applying patch /nix/store/bp10sc939dswqh14zyszri157qf4hixi-openssl-tls-28.patch
patching file include/openssl/tls1.h
patching file util/perl/TLSProxy/Record.pm
configuring
patching script interpreter paths in Configure
Configure: interpreter directive changed from " /usr/bin/env perl" to "/nix/store/vawc9a89l53mf05yq0k1910q7dakd99w-perl-5.24.3/bin/perl"
configure flags: --prefix=/nix/store/69s4p101g80n387zncpcij2cal6lbkp6-openssl-1.1.1-pre6 shared --libdir=lib --openssldir=etc/ssl
Operating system: x86_64-whatever-linux2
./config: eval: line 1: /usr/bin/env: not found
building
build flags: -j1 -l1 SHELL=/nix/store/8zkg9ac4s4alzyf4a8kfrig1j73z66dw-bash-4.4-p23/bin/bash MANDIR=\$\(man\)/share/man
make: *** No targets specified and no makefile found.  Stop.
builder for '/nix/store/3scr6k66kicpa7r09iski3v5p5zd92pj-openssl-1.1.1-pre6.drv' failed with exit code 2
error: build of '/nix/store/3scr6k66kicpa7r09iski3v5p5zd92pj-openssl-1.1.1-pre6.drv' failed
direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +IN_NIX_SHELL +LD +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_x86_64_unknown_linux_gnu_TARGET_HOST +NIX_BUILD_CORES +NIX_BUILD_TOP +NIX_CC +NIX_CC_WRAPPER_x86_64_unknown_linux_gnu_TARGET_HOST +NIX_CFLAGS_COMPILE +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_LDFLAGS +NIX_STORE +NM +OBJCOPY +OBJDUMP +PKG_CONFIG_PATH +RANLIB +READELF +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +TEMP +TEMPDIR +TMP +TMPDIR +WINDRES +_PATH +buildInputs +builder +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostBuild +depsHostBuildPropagated +depsTargetTarget +depsTargetTargetPropagated +name +nativeBuildInputs +out +propagatedBuildInputs +propagatedNativeBuildInputs +shell +stdenv +strictDeps +system ~DBUS_SESSION_BUS_ADDRESS ~PATH ~WINDOWID
```

Which is weird since `/usr/bin/env` is definitely present on my system.

At this point I'm just gonna wait til rusttls is usable or openssl release a new version.

**Comment by Ralith** [comment]
Development is moving to https://github.com/djc/quinn, where a rustls port of quicr's existing code has already been completed thanks to great work from @djc.
